---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r include=FALSE}
library(ggplot2)
library(reshape2)
library(stringr)
```

## Including Plots


```{r pressure, echo=FALSE}
data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/CAGE_K562.txt", sep = "\t", header = T)

rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)

peaks = NULL
temp = melt(as.matrix(data))
temp$source = "Covid_ATSMIX"
temp$cell = "K562"
peaks = rbind(peaks, temp)
```


```{R}
ggplot(temp, aes(x=Var1, y=value, color=Var2)) +
  geom_line() +
  facet_wrap(.~Var2) +
  theme_pubr() +
  labs(x = "", y="", title = "K562") +
  theme(legend.position = "none")
```


```{r pressure, echo=FALSE}
data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/CAGE_GM12878", sep = "\t", header = T)

rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)

temp = melt(as.matrix(data))
temp$cell = "GM12878"
temp$source = "Covid_ATSMIX"
peaks = rbind(peaks, temp)
```


```{R}
ggplot(temp, aes(x=Var1, y=value, color=Var2)) +
  geom_line() +
  facet_wrap(.~Var2) +
  theme_pubr() +
  labs(x = "", y="", title = "GM12878") +
  theme(legend.position = "none")
```


```{r pressure, echo=FALSE}
data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/NSLC_A549", sep = "\t", header = T)

rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)

temp = melt(as.matrix(data))
temp$cell = "A549"
temp$source = "NSLC_ATSMIX"
peaks = rbind(peaks, temp)
```


```{R}
ggplot(temp, aes(x=Var1, y=value, color=Var2)) +
  geom_line() +
  facet_wrap(.~Var2) +
  theme_pubr() +
  labs(x = "", y="", title = "CAGE GM12878") +
  theme(legend.position = "none")
```


```{r pressure, echo=FALSE}
data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/CTSS_K562", sep = "\t", header = T)

rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)

temp = melt(as.matrix(data))
temp$cell = "K562"
temp$source = "CAGE"
peaks = rbind(peaks, temp)
```


```{R}
ggplot(temp, aes(x=Var1, y=value, color=Var2)) +
  geom_line() +
  facet_wrap(.~Var2) +
  theme_pubr() +
  labs(x = "", y="", title = "CAGE K562") +
  theme(legend.position = "none")
```


````{r pressure, echo=FALSE}
data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/CTSS_GM12878", sep = "\t", header = T)

rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)

temp = melt(as.matrix(data))
temp$cell = "GM12878"
temp$source = "CAGE"
peaks = rbind(peaks, temp)
```


```{R}
ggplot(temp, aes(x=Var1, y=value, color=Var2)) +
  geom_line() +
  facet_wrap(.~Var2) +
  theme_pubr() +
  labs(x = "", y="", title = "CAGE K562") +
  theme(legend.position = "none")
```


````{r pressure, echo=FALSE}
data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/CTSS_A549", sep = "\t", header = T)

rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)

temp = melt(as.matrix(data))
temp$cell = "A549"
temp$source = "CAGE"
peaks = rbind(peaks, temp)
```


```{R}
ggplot(temp, aes(x=Var1, y=value, color=Var2)) +
  geom_line() +
  facet_wrap(.~Var2) +
  theme_pubr() +
  labs(x = "", y="", title = "CAGE K562") +
  theme(legend.position = "none")
```

```{r pressure, echo=FALSE}
data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/promoter_K562", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "K562"
temp$source = "Promoter"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/promoter_GM12878", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "GM12878"
temp$source = "Promoter"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/promoter_A549", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "A549"
temp$source = "Promoter"
peaks = rbind(peaks, temp)

peaks = peaks[peaks$source != "CAGE", ]

data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/hglft_K562", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "K562"
temp$source = "CAGE"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/hglft_GM12878", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "GM12878"
temp$source = "CAGE"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/hglft_A549", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "A549"
temp$source = "CAGE"
peaks = rbind(peaks, temp)

```

```{r fig.height=4, fig.width=6}
pdf("/mnt/raid64/ATS/Personal/zhangyiming/quant/histone_markers.pdf", width = 6, height = 4)
for (i in unique(peaks$cell)) {
    p <- ggplot(peaks[peaks$cell == i, ], aes(x=Var1, y=value, color=source)) +
      geom_line() +
      facet_wrap(.~Var2, scales = "free") +
      theme_pubr() +
      labs(title = i, x = "Distance to TSS (bp)", y="Average Cov")
    print(p)
}
dev.off()

saveRDS(peaks, "/mnt/raid64/ATS/Personal/zhangyiming/quant/histone_markers.rds")
```


```{r}
peaks = NULL
data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/mmlft_B", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "B"
temp$source = "CAGE"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/mmlft_MK", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "MK"
temp$source = "CAGE"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/mmlft_MPP", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "Mφ"
temp$source = "CAGE"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/CAGE_B", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "B"
temp$source = "ATSMix"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/CAGE_MK", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "MK"
temp$source = "ATSMix"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/CAGE_MPP", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "Mφ"
temp$source = "ATSMix"
peaks = rbind(peaks, temp)
```


```{r fig.height=4, fig.width=6}
pdf("/mnt/raid64/ATS/Personal/zhangyiming/quant/histone_markers_mm.pdf", width = 6, height = 3)
for (i in unique(peaks$cell)) {
    p <- ggplot(peaks[peaks$cell == i, ], aes(x=Var1, y=value, color=source)) +
      geom_line() +
      facet_wrap(.~Var2, scales = "free") +
      theme_pubr() +
      labs(title = i, x = "Distance to TSS (bp)", y="Average Cov")
    print(p)
}
dev.off()

saveRDS(peaks, "/mnt/raid64/ATS/Personal/zhangyiming/quant/histone_markers_mm.rds")
```




```{r}
peaks = NULL
data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/cell_K562", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "K562"
temp$source = "Cell"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/cell_GM12878", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "GM12878"
temp$source = "Cell"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/hg19_K562", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "K562"
temp$source = "CAGE"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/hg19_GM12878", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "GM12878"
temp$source = "CAGE"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/cell_sel_K562", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "K562"
temp$source = "Cell_filtered"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/cell_sel_GM12878", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "GM12878"
temp$source = "Cell_filtered"
peaks = rbind(peaks, temp)



data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/cell_2_K562", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "K562"
temp$source = "Cell_2"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/cell_2_GM12878", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "GM12878"
temp$source = "Cell_2"
peaks = rbind(peaks, temp)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/stats/cell_3_GM12878", sep = "\t", header = T)
rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
temp = melt(as.matrix(data))
temp$cell = "GM12878"
temp$source = "Cell_3"
peaks = rbind(peaks, temp)
```


```{r fig.height=4, fig.width=6}
pdf("/mnt/raid64/ATS/Personal/zhangyiming/quant/histone_markers_cell.pdf", width = 6, height = 4)
for (i in unique(peaks$cell)) {
    p <- ggplot(peaks[peaks$cell == i & peaks$source %in% c("CAGE", "Cell_", "Cell_3"), ], aes(x=Var1, y=value, color=source)) +
      geom_line() +
      facet_wrap(.~Var2, scales = "free") +
      ggpubr::theme_pubr() +
      labs(title = i, x = "Distance to TSS (bp)", y="Average Cov")
      # scale_x_continuous(breaks = seq(-2000, 2000, by = 100)) +
      # theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))
    print(p)
}
dev.off()

saveRDS(peaks, "/mnt/raid64/ATS/Personal/zhangyiming/quant/histone_markers_cell.rds")
```

```{R}
data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/overall_ATS_cage_R.txt", header = T, stringsAsFactors = F)

data$num = sapply(data$ats_arr, function(x) {
  length(str_split(x, ",")[[1]])
})

temp = as.data.frame(table(data$n))
temp$p = temp$Freq / sum(temp$Freq) * 100

labs <- paste0(temp$num, " (", round(temp$p, 2), "%)")

temp$num = as.character(temp$Var1)

p1 = ggpie(
  temp, "Freq", 
  label = labs,
  fill = "num", color = "white", 
  lab.pos = "in",
  title = "Covid"
)


data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/overall_ATS_nslc.txt", header = T, stringsAsFactors = F)

data$num = sapply(data$ats_arr, function(x) {
  length(str_split(x, ",")[[1]])
})

temp = as.data.frame(table(data$n))
temp$p = temp$Freq / sum(temp$Freq) * 100
temp$num = as.character(temp$Var1)

labs <- paste0(temp$num, " (", round(temp$p, 2), "%)")


p2 = ggpie(
  temp, "Freq", 
  label = labs,
  fill = "num", color = "white", 
  lab.pos = "in",
  title = "NSLC"
)

data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/overall_ATS_mm1.txt", header = T, stringsAsFactors = F)
data$num = sapply(data$ats_arr, function(x) {
  length(str_split(x, ",")[[1]])
})

temp = as.data.frame(table(data$n))
temp$p = temp$Freq / sum(temp$Freq) * 100
temp$num = as.character(temp$Var1)

labs <- paste0(temp$num, " (", round(temp$p, 2), "%)")

p3 = ggpie(
  temp, "Freq", 
  label = labs,
  fill = "num", color = "white", 
  lab.pos = "in",
  title = "Mouse"
)

ggsave(
  filename = "/mnt/raid64/ATS/Personal/zhangyiming/quant/pie.pdf",
  width = 12, height = 4, plot = cowplot::plot_grid(p1, p2, p3, nrow = 1)
)



data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/overall_STAT1.txt", header = T, stringsAsFactors = F)
data$num = sapply(data$ats_arr, function(x) {
  length(str_split(x, ",")[[1]])
})


data = read.table("/mnt/raid61/Personal_data/zhangyiming/ePSI/ats/overall1.txt", header = T, stringsAsFactors = F)
data$num = sapply(data$ats_arr, function(x) {
  length(str_split(x, ",")[[1]])
})


data = read.table("/mnt/raid61/Personal_data/zhangyiming/ePSI/ats/overall_200.txt", header = T, stringsAsFactors = F)
data$num = sapply(data$ats_arr, function(x) {
  length(str_split(x, ",")[[1]])
})


write.table(data[data$num > 1 & data$num < 3, ], "/mnt/raid61/Personal_data/zhangyiming/ePSI/ats/overall_200_sel.txt", row.names = F, quote = F, sep = "\t")
```


```{r fig.height=4, fig.width=6}
freq = NULL
for (i in list.files("/mnt/raid64/ATS/Personal/zhangyiming/infered/", pattern = "txt$", full.names = T)) {
  data = read.table(i, header = T, stringsAsFactors = F)

  data$num = sapply(data$ats_arr, function(x) {
    length(str_split(x, ",")[[1]])
  })
  
  temp = as.data.frame(table(data$n))
  temp$source = str_replace_all(basename(i), ".txt", "")
  temp$p = temp$Freq / sum(temp$Freq) * 100
  
  freq = rbind(freq, temp)
}

data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/overall_ATS_cage_R.txt", header = T, stringsAsFactors = F)

data$num = sapply(data$ats_arr, function(x) {
  length(str_split(x, ",")[[1]])
})

temp = as.data.frame(table(data$n))
temp$source = "Mixed COVID-19"
temp$p = temp$Freq / sum(temp$Freq) * 100

freq = rbind(freq, temp)

freq$Var1 = factor(
  as.character(freq$Var1), 
  levels = rev(as.character(unique(freq$Var1)))
)


lvls = c()
for (i in c("PHC", "PCov", "NHC",  "NCovM", "NCovS")) {
  lvls = c(lvls, unique(freq$source)[str_detect(unique(freq$source), i)])
}

freq$source = factor(freq$source, levels = c(lvls, "Mixed COVID-19"))

p <- ggplot(freq, aes(x=source, y=p, fill=Var1))  +
  geom_bar(stat = "identity") +
  ggpubr::theme_pubr() +
  labs(x = "Sample ID", y = "Fraction of UTRs (%)", fill = "Number of ATS") +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)
  )

ggsave(
  filename = "/mnt/raid64/ATS/Personal/zhangyiming/quant/num_of_ATS_covid19.pdf",
  plot = p, width = 6, height = 4
)
```


## compare different standard

```{r}
fs = list.files("/mnt/raid64/ATS/Personal/zhangyiming/cage_sel_hm/",  pattern = "_.txt", full.names = T)

peaks = NULL
for (f in fs) {
    key = str_replace_all(basename(f), "(peak_region_|_.txt)", "")
    key = str_split(key, "_")[[1]]
    data = read.table(f, sep = "\t", header = T)

    rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)
    temp = melt(as.matrix(data))
    temp = temp[temp$Var2 != "CTCF", ]
    temp$freq = as.numeric(key[1])
    temp$count  = as.numeric(key[2])
   
    peaks = rbind(peaks, temp)
}
```


```{r fig.height=10, fig.width=10}
for (i in unique(peaks$Var2)) {
    p <- ggplot(peaks[peaks$Var2 == i, ], aes(x=Var1, y=value, color = Var2)) +
        geom_line() + labs(title = i) +
        facet_grid(freq~count)
    print(p)
}
```


```{R}
test_xu <- read.delim("/mnt/raid64/ATS/Personal/zhangyiming/NHC2")

data = test_xu[test_xu$alpha_arr != "", ]
len_list = vector('list',length=nrow(test_xu))
for(i in seq(nrow(test_xu))){
  st_arr = as.numeric(strsplit(as.character(test_xu[i,'st_arr']),',')[[1]])
  en_arr = as.numeric(strsplit(as.character(test_xu[i,'en_arr']),',')[[1]])
  len_list[[i]] = st_arr-en_arr
}
len_arr = unlist(len_list)
plot.new()
plot(density(abs(len_arr)),title('fragment size distribution'),xlim=c(0,500))

```


```{r pressure, echo=FALSE}
data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/peaks/NHC2", sep = "\t", header = T)

rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)

# temp = apply(data, 2, function(col) {
#     col / sum(col)
# })
temp = data

temp = melt(as.matrix(temp))
temp = temp[temp$Var2 != "CTCF", ]
temp$source = "Annotation"
# peaks = rbind(peaks, temp)
```


```{R}
ggplot(temp, aes(x=Var1, y=value, color=Var2)) +
    geom_line() +
    facet_wrap(.~Var2)
```


```{R}
test_xu <- read.delim("/mnt/raid64/ATS/Personal/zhangyiming/NHC2_jl")

data = test_xu[test_xu$alpha_arr != "", ]
len_list = vector('list',length=nrow(test_xu))
for(i in seq(nrow(test_xu))){
  st_arr = as.numeric(strsplit(as.character(test_xu[i,'st_arr']),',')[[1]])
  en_arr = as.numeric(strsplit(as.character(test_xu[i,'en_arr']),',')[[1]])
  len_list[[i]] = st_arr-en_arr
}
len_arr = unlist(len_list)
len_arr = len_arr[abs(len_arr)> 10]
plot.new()
plot(density(abs(len_arr)),title('fragment size distribution'),xlim=c(0,500))

```

```{r pressure, echo=FALSE}
data = read.table("/mnt/raid64/ATS/Personal/zhangyiming/peaks/NHC2_jl_all", sep = "\t", header = T)

rownames(data) = seq(-nrow(data) / 2 + 1, nrow(data)/2)

# temp = apply(data, 2, function(col) {
#     col / sum(col)
# })
temp = data

temp = melt(as.matrix(temp))
temp = temp[temp$Var2 != "CTCF", ]
temp$source = "Annotation"
# peaks = rbind(peaks, temp)
```


```{R}
ggplot(temp, aes(x=Var1, y=value, color=Var2)) +
    geom_line() +
    facet_wrap(.~Var2)
```



## STRT
```{r fig.height=5, fig.width=5}
data = read.csv("/mnt/raid64/ATS/Personal/zhangyiming/STRT_QC/stats.csv", stringsAsFactors = F, header = F)

data$align = data$V3 / data$V2
data$not =  data$V4 / data$V3
data$uniq = 1 - data$not

temp = melt(data[, c("not", "uniq")])


ggplot(data, aes(x=V3, y=uniq)) +
  geom_point()


p <- ggpubr::ggscatter(data, x="V3", y="uniq", xlab = "Number of aligned reads", ylab="Uniquely mapped (%)")

ggsave(
  filename = "/mnt/raid64/ATS/Personal/zhangyiming/quant/STRT_um.pdf",
  plot = p, width = 5, height = 5
)
```


```{r}
VlnPlot(obj, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size  = 0, group.by = "Patient")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
